"""Excepciones: continuación"""
# Observa el código en el editor. Ejecuta el (obviamente incorrecto) programa.

val=1
val/=0

# Verás el siguiente mensaje en respuesta:

# Traceback (most recent call last):
# File "div.py", line 2, in 
# value /= 0
# ZeroDivisionError: division by zero

# Este error es llamado ZeroDivisionError.

